services:
  db:
    image: postgres:latest
    container_name: postgres_analitica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: analitica_inversiones
    ports:
      - "5433:5432"
    restart: unless-stopped
