# Generated by Django 6.1.1 on 2026-10-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioCOP',
            fields=[
                ('id_sistema_cliente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_corte', models.DateField()),
                ('id_aproximado', models.BooleanField(default=False)),
                ('cod_activo', models.CharField(max_length=50, null=True)),
                ('nombre_activo', models.CharField(max_length=255)),
                ('macroactivo', models.CharField(max_length=100)),
                ('perfil_riesgo', models.CharField(max_length=100)),
                ('banca', models.CharField(max_length=100)),
                ('saldo_cop', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
            options={
                'db_table': 'vista_portafolio_cop_ultimo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PortafolioUSD',
            fields=[
                ('id_sistema_cliente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_corte', models.DateField()),
                ('id_aproximado', models.BooleanField(default=False)),
                ('simbolo', models.CharField(max_length=50, null=True)),
                ('cusip', models.CharField(max_length=50, null=True)),
                ('isin', models.CharField(max_length=50, null=True)),
                ('nombre_activo', models.CharField(max_length=255)),
                ('tipo_activo', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('saldo_usd', models.DecimalField(decimal_places=2, max_digits=24)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('tasa_cupon', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'vista_portafolio_usd_ultimo',
                'managed': False,
            },
        ),
    ]
